# Generated by Django 3.0.5 on 2020-04-19 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordinance', '0002_auto_20200419_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='studends',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='educator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_educator', to=settings.AUTH_USER_MODEL),
        ),
    ]
