# Generated by Django 3.0.5 on 2020-04-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordinance', '0003_auto_20200419_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='educator',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='studends',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
    ]
