# Generated by Django 3.0.5 on 2020-04-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinance', '0004_auto_20200420_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
            ],
        ),
    ]
