# Generated by Django 3.0.5 on 2020-04-22 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordinance', '0005_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordinance.Classroom'),
        ),
    ]
