# Generated by Django 3.0.5 on 2020-04-22 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordinance', '0007_auto_20200422_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='Subjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordinance.Subject'),
        ),
    ]
