# Generated by Django 3.0.5 on 2020-04-23 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordinance', '0009_auto_20200422_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='Subjects',
            new_name='subjects',
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recived', models.DateTimeField(auto_now_add=True, verbose_name='data recived')),
                ('data_send', models.DateTimeField(auto_now_add=True, verbose_name='data_send')),
                ('rote', models.IntegerField()),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='tasks',
            field=models.ManyToManyField(to='ordinance.Tasks'),
        ),
    ]
