# Generated by Django 3.0.5 on 2020-04-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinance', '0010_auto_20200423_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='data_recived',
            field=models.BooleanField(default=False),
        ),
    ]
