# Generated by Django 3.0.5 on 2020-04-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinance', '0011_auto_20200424_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='taskfile',
            field=models.FileField(null=True, upload_to='books/pdfs/'),
        ),
    ]
