# Generated by Django 3.0.5 on 2020-04-28 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordinance', '0012_lesson_taskfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='tasks',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='taskfile',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='Dodaj Plik'),
        ),
    ]
