# Generated by Django 3.0.5 on 2020-04-28 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordinance', '0013_auto_20200428_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='tasks',
            new_name='students',
        ),
        migrations.AddField(
            model_name='tasks',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson', to='ordinance.Lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tasks',
            field=models.ManyToManyField(related_name='tasks', to='ordinance.Tasks'),
        ),
    ]
