# Generated by Django 3.0.5 on 2020-04-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinance', '0014_auto_20200428_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='taskfile',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='Dodaj Zadanie'),
        ),
    ]
