# Generated by Django 3.0.5 on 2020-04-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinance', '0015_tasks_taskfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='data_send',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='data_recived',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data recived'),
        ),
    ]
