# Generated by Django 3.0.5 on 2020-04-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinance', '0017_auto_20200428_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='taskfile',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tasks',
            field=models.ManyToManyField(to='ordinance.Tasks'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='data_recived',
            field=models.BooleanField(default=False),
        ),
    ]
