# Generated by Django 3.0.5 on 2020-04-28 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordinance', '0018_auto_20200428_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='lessons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson', to='ordinance.Lesson'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='taskfile',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='Dodaj Plik'),
        ),
    ]
