# Generated by Django 3.0.5 on 2020-05-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinance', '0019_auto_20200428_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashbord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=240, verbose_name='Nagłówek')),
                ('description', models.TextField(verbose_name='Treść')),
            ],
        ),
    ]
