# Generated by Django 3.0.5 on 2020-05-05 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0013_auto_20200427_1541'),
        ('ordinance', '0020_dashbord'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashbord',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='Dodaj Plik'),
        ),
        migrations.AddField(
            model_name='dashbord',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place', to='authorization.AccountType', verbose_name='Typ uprawnień'),
        ),
    ]
