# Generated by Django 3.0.5 on 2020-05-05 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordinance', '0021_auto_20200505_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashbord',
            name='data',
            field=models.DateTimeField(null=True, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='dashbord',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='ordinance.Lesson'),
        ),
    ]
