# Generated by Django 3.0.5 on 2020-05-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinance', '0023_auto_20200505_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashbord',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
