# Generated by Django 3.0.5 on 2020-05-06 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinance', '0026_dashbord_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='rotedata',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 15, 11, 5, 869087)),
        ),
    ]
