# Generated by Django 3.0.5 on 2020-04-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinance', '0004_auto_20200420_1338'),
        ('authorization', '0007_auto_20200420_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_teacher',
            field=models.ManyToManyField(null=True, to='ordinance.Subject'),
        ),
    ]
