# Generated by Django 3.0.5 on 2020-04-22 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordinance', '0005_lesson'),
        ('authorization', '0008_auto_20200420_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='imię'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_educator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educator', to='ordinance.Classroom', verbose_name='Czy jest wychowcą dodaj klase  ? (jesli nie pomiń)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='ordinance.Classroom', verbose_name='Czy jest studentem ? (jesli nie pomiń)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_teacher',
            field=models.ManyToManyField(blank=True, null=True, to='ordinance.Subject', verbose_name='Czy jest nauczycielem dodaj przemioty jakie uczy ? (jesli nie pomiń)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='nazwisko'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type', to='authorization.AccountType', verbose_name='Typ uprawnień'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
