# Generated by Django 3.0.5 on 2020-04-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0010_account_classroos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='classroos',
            new_name='classrooms',
        ),
    ]
