# Generated by Django 3.0.5 on 2020-04-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinance', '0012_lesson_taskfile'),
        ('authorization', '0012_auto_20200422_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='classromms', to='ordinance.Classroom', verbose_name='Jeśli jest nauczycielem to jakich przemiotów uczy ? (jesli nie to pomiń)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_teacher',
            field=models.ManyToManyField(blank=True, to='ordinance.Subject', verbose_name='Czy jest nauczycielem dodaj przemioty jakie uczy ? (jesli nie pomiń)'),
        ),
    ]
